### ISSUE TITLE
JSON limit order create

### ISSUE THREAD

**Issue by thontron** [bitshares/beet-js#26]
I tried to import a limit order operation to the transaction builder. The example had a transfer which I believe is different syntax from a limit order. I have the json copied below:
```
{
    "expiration": "2019-06-29T16:41:16",
    "operations": [
        [
            1,
            {
                "expiration": "2019-06-30T16:40:23",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 649045361,
                    "asset_id": "1.3.0"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 31054802,
                    "asset_id": "1.3.113"
                },
                "extensions": []
            }
        ],
        [
            1,
            {
                "expiration": "2019-06-30T16:40:24",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 55809766,
                    "asset_id": "1.3.113"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 1205490946,
                    "asset_id": "1.3.0"
                },
                "extensions": []
            }
        ]
    ],
    "extensions": [],
    "ref_block_num": 24162,
    "signatures": [],
    "ref_block_prefix": 4066567281
}
```

**Comment by sschiessl-bcp** [comment]
First glance looks fine. What error do You see?

**Comment by thontron** [comment]
Just nothing happens when I swap it in stead of: 

// build transfer operation
            let  tr = new TransactionBuilder();
            let transfer_op = tr.get_type_operation("transfer", {
                fee: {
                    amount: 0,
                    asset_id: "1.3.0"
                },
                from: app.BTS.getAccount().id,
                to: "1.2.886902",
                amount: {amount: 100, asset_id: "1.3.0"},
                memo: undefined
            });
            tr.add_operation(
                transfer_op 
            );

Also is that original example syntax a json? It looks a little different.

Thanks for your help.

**Comment by sschiessl-bcp** [comment]
Please surroung your code with ```, makes it easier to read

**Comment by sschiessl-bcp** [comment]
Could you please post the example you are trying to get working, and doesnt work atm?

**Comment by thontron** [comment]
Here is the example am trying to use. Beet does not activate with this. Though I only replaced the first second above code (tx builder) with the first above code (json order).

'''
<script>
    let init = async function() {
        try {
            // establish connection to beet
            let app = await beet.get("BitShares Injection Example", "BTS");

            // inject beet
            TransactionBuilder = app.BTS.inject(bitshares_js.TransactionBuilder);

            console.log(app.BTS.getAccount());

            // connect to bitshares blockchain
            await bitshares_js.bitshares_ws.Apis.instance(
                "wss://eu.nodes.bitshares.ws",
                true,
                10000,
                {enableCrypto: false, enableOrders: false},
                (err) => console.log(err)
            ).init_promise;

            // build transfer operation
            let  tr = new TransactionBuilder();
            let transfer_op = tr.get_type_operation("limit_order_create", {
            "expiration": "2019-06-29T16:41:16",
            "operations": [
             [
            1,
            {
                "expiration": "2019-06-30T16:40:23",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 649045361,
                    "asset_id": "1.3.0"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 31054802,
                    "asset_id": "1.3.113"
                },
                "extensions": []
            }
             ],
             [
            1,
            {
                "expiration": "2019-06-30T16:40:24",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 55809766,
                    "asset_id": "1.3.113"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 1205490946,
                    "asset_id": "1.3.0"
                },
                "extensions": []
            }
                ]
             ],
            "extensions": [],
            "ref_block_num": 24162,
             "signatures": [],
            "ref_block_prefix": 4066567281
        } catch (err) {
            console.error(err);
        }
    };
    init();
</script>
'''

**Comment by thontron** [comment]
`<script>
    let init = async function() {
        try {
            // establish connection to beet
            let app = await beet.get("BitShares Injection Example", "BTS");

            // inject beet
            TransactionBuilder = app.BTS.inject(bitshares_js.TransactionBuilder);

            console.log(app.BTS.getAccount());

            // connect to bitshares blockchain
            await bitshares_js.bitshares_ws.Apis.instance(
                "wss://eu.nodes.bitshares.ws",
                true,
                10000,
                {enableCrypto: false, enableOrders: false},
                (err) => console.log(err)
            ).init_promise;

            // build transfer operation
            let  tr = new TransactionBuilder();
            let transfer_op = tr.get_type_operation("limit_order_create", {
            "expiration": "2019-06-29T16:41:16",
            "operations": [
             [
            1,
            {
                "expiration": "2019-06-30T16:40:23",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 649045361,
                    "asset_id": "1.3.0"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 31054802,
                    "asset_id": "1.3.113"
                },
                "extensions": []
            }
             ],
             [
            1,
            {
                "expiration": "2019-06-30T16:40:24",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 55809766,
                    "asset_id": "1.3.113"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 1205490946,
                    "asset_id": "1.3.0"
                },
                "extensions": []
            }
                ]
             ],
            "extensions": [],
            "ref_block_num": 24162,
             "signatures": [],
            "ref_block_prefix": 4066567281
        } catch (err) {
            console.error(err);
        }
    };
    init();
</script>

**Comment by thontron** [comment]
`<script>
    let init = async function() {
        try {
            // establish connection to beet
            let app = await beet.get("BitShares Injection Example", "BTS");

            // inject beet
            TransactionBuilder = app.BTS.inject(bitshares_js.TransactionBuilder);

            console.log(app.BTS.getAccount());

            // connect to bitshares blockchain
            await bitshares_js.bitshares_ws.Apis.instance(
                "wss://eu.nodes.bitshares.ws",
                true,
                10000,
                {enableCrypto: false, enableOrders: false},
                (err) => console.log(err)
            ).init_promise;

            // build transfer operation
            let  tr = new TransactionBuilder();
            let transfer_op = tr.get_type_operation("limit_order_create", {
            "expiration": "2019-06-29T16:41:16",
            "operations": [
             [
            1,
            {
                "expiration": "2019-06-30T16:40:23",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 649045361,
                    "asset_id": "1.3.0"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 31054802,
                    "asset_id": "1.3.113"
                },
                "extensions": []
            }
             ],
             [
            1,
            {
                "expiration": "2019-06-30T16:40:24",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 143,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 55809766,
                    "asset_id": "1.3.113"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 1205490946,
                    "asset_id": "1.3.0"
                },
                "extensions": []
            }
                ]
             ],
            "extensions": [],
            "ref_block_num": 24162,
             "signatures": [],
            "ref_block_prefix": 4066567281
        } catch (err) {
            console.error(err);
        }
    };
    init();
</script>

**Comment by sschiessl-bcp** [comment]
Try this
```
<script>
    let init = async function() {
        try {
            // establish connection to beet
            let app = await beet.get("BitShares Injection Example", "BTS");

            // inject beet
            TransactionBuilder = app.BTS.inject(bitshares_js.TransactionBuilder);

            console.log(app.BTS.getAccount());

            // connect to bitshares blockchain
            await bitshares_js.bitshares_ws.Apis.instance(
                "wss://eu.nodes.bitshares.ws",
                true,
                10000,
                {enableCrypto: false, enableOrders: false},
                (err) => console.log(err)
            ).init_promise;

            // build transfer operation
            let  tr = new TransactionBuilder();
            let transfer_op = tr.get_type_operation("transfer", {
                fee: {
                    amount: 0,
                    asset_id: "1.3.0"
                },
                from: app.BTS.getAccount().id,
                to: "1.2.886902",
                amount: {amount: 100, asset_id: "1.3.0"},
                memo: undefined
            });
            tr.add_operation(
                transfer_op
            );
            let order_op = tr.get_type_operation("limit_order_create", {
                "expiration": "2019-07-02T16:40:24",
                "seller": "1.2.1595919",
                "fee": {
                    "amount": 0,
                    "asset_id": "1.3.113"
                },
                "amount_to_sell": {
                    "amount": 55809766,
                    "asset_id": "1.3.113"
                },
                "fill_or_kill": false,
                "min_to_receive": {
                    "amount": 1205490946,
                    "asset_id": "1.3.0"
                },
                "extensions": []
            });
            tr.add_operation(
                order_op
            );
            await tr.set_required_fees();
            await tr.update_head_block();
            tr.add_signer("inject_wif");
            await tr.broadcast();
        } catch (err) {
            console.error(err);
        }
    };
    init();
</script>
```

**Comment by thontron** [comment]
@sschiessl-bcp Thank you. This does prompt beet app to recognize and build. But did not broadcast. Has that ever happened?

**Comment by sschiessl-bcp** [comment]
Are you running latest beet version? If so, click the upper right "bug" icon and show me what the console says after approving the request.

**Comment by thontron** [comment]
Great - pm'd the log file from console.
