### ISSUE TITLE
Inconsistent trade sell/price fields?

### ISSUE THREAD

**Issue by grctest** [bitshares/beet-js#42]
I have an NFT for sale at 20000 BTS, when I fetch this bid from openexplorer api I have to perform `1/bids[0].price` to get "20000 BTS"

However when I create a beet limit_order_create I have to perform `100000/bids[0].price` to get 20000 BTS:

```
let transfer_op = tr.get_type_operation("limit_order_create", {
    fee: {
        amount: 0,
        asset_id: "1.3.0"
    },
    seller: account.id,
    amount_to_sell: {
      amount: ${100000/bids[0].price},
      asset_id: "${approvedMarketID}"
    },
    min_to_receive: {
      amount: 1,
      asset_id: "${symbolID}"
    },
    fill_or_kill: true,
    expiration: 100000
});
```

![image](https://user-images.githubusercontent.com/15861527/141841466-b43c775d-d105-4d34-9326-e84bab9936c1.png)

However NFTEA.F3 with a price of `31705.300007503152 BTS` (31,705.3 in DEX) (shown with 1\bids[0].price) when applied with `100000/bids[0].price` results in ` Sell: 317053000000.00006 BTS`:

![image](https://user-images.githubusercontent.com/15861527/141842003-e383c8c2-11d5-4b53-a625-d1054368ce67.png)

What's the correct calculation I should be performing for these amount_to_sell & min_to_receive fields? It seems inconsistent? Is the above error due to the large quantity of BTS decimal places?

**Comment by grctest** [comment]
Fixed using the following:
```
amount_to_sell: {
  amount: ${bids[0].quote*100000},
  asset_id: "${approvedMarketID}"
},
```

**Comment by sschiessl-bcp** [comment]
I don't quite follow what the initial problem was, I'm glad you could get it fixed though :)
